export class ParameterDetail {
    parameterDetailId: number;
    parameterId: number;
    description: string;
    field1: string;
    field2: string;
    field3: string;
    field4: string;
    field5: string;
    field6: string;
    field7: string;
    field8: string;
    field9: string;
    field10: string;
    field11: string;
    field12: string;
    field13: string;
    field14: string;
    fieldDescription1: string;
    fieldDescription2: string;
    fieldDescription3: string;
    fieldDescription4: string;
    fieldDescription5: string;
    fieldDescription6: string;
    fieldDescription7: string;
    fieldDescription8: string;
    fieldDescription9: string;
    fieldDescription10: string;
    fieldDescription11: string;
    fieldDescription12: string;
    fieldDescription13: string;
    fieldDescription14: string;
    observation:string;
}