export const environment = {
  production: false,
  hmr: false,
  api: {
    customers: 'https://api.realplazalabs.com/v1/customers',
    contracts: 'http://18.218.163.86/precontratos/contracts',
    advance: 'https://api.realplazalabs.com/common/advance',
    storage: 'https://api.realplazalabs.com/v1/storage',
    security: 'https://api.realplazalabs.com/v1/oauth'
  },
  advance: {
    get_parameter_detail: '/parameterdetails/search?parameterId={0}',
    get_parameter_detail_template: '/parameterdetails/search?parameterId={0}&field1={1}',
    get_deparments: '/ubigeo/departments',
    get_provinces: '/ubigeo/provinces?departmentId={0}',
    get_districts: '/ubigeo/districts?provinceId={0}',
    get_tradenames: '/tradenames/search',
    get_state_workflow: '/state-workflow/search?entityId={0}',
    get_state_workflow_template: '/state-workflow/search?entities={0}',
    get_currencys: '/currencys/search?CurrencyId={0}',
    get_malls: '/malls/search',
    get_locals: '/locals/find-all?PropertyId={0}',
    get_concept: '/concepts/search',
    get_local_search: '/locals/search',
    get_local_current_situation: '/locals/current-situation',
    get_item_search: '/item-components/search',
    get_sub_item_seach: '/sub-items/search',
    get_tradename_by_customerid: '/tradenames/tradename-customer',
    get_local_types: '/local-types/search',
    get_colaborator_by_document: '/collaborators/{0}',
    get_mall_by_id: '/malls/{0}',
    get_tradename_by_id: '/tradenames/{0}',
    get_local_executive_search: '/local-executives/search',
    post_local_executive: '/local-executives'
  },
  customer: {
    get_customers: '/customerstandard',
    get_contactsXDocument: "/contacts/?DocumentId={0}&Active={1}",
    get_addressesxDocument: "/addresses/?DocumentId={0}&Active={1}",
    get_tradenames: "/tradenamestandard/{0}",
    get_mails: "/mails?DocumentId={0}",
    get_custromers_search: '/',
    get_customers_by_document: '/{0}',
    get_customer_credit_evaluation_collection: '/credit-evaluation-collection/search',
    get_tradename_rubro_search : '/tradenamerubros/search',
    get_IdSumma: '/sellers/idsumma/search',
    post_tradenamerubros: '/tradenamerubros',
    post_tradenamerubros_approve: '/tradenamerubros/approve'
  },
  contracts: {
    get_commercial_templates: "/commercial-templates/inbox?commercial_template_id={0}&customer_id={1}&tradename_id={2}{3}{4}{5}{6}&pageIndex={7}&pageSize={8}&sort={9}&user_id={10}",
    get_commercial_templates_search: "/commercial-templates/search/?commercial_template_id={0}",
    get_commercial_templates_tradenames_findall: "/commercial-templates/tradenames/find-all/?commercial_template_id={0}&pageIndex={1}&pageSize={2}&sort={3}",
    get_tradenames_commercial_templates: "/commercial-templates/tradenames/search?commercial_template_id={0}",
    get_platforms_commercial_template: "/commercial-templates/platforms/search?commercial_template_id={0}",
    get_fixed_validity_commercial_template: "/commercial-templates/fixed-validitys/search?commercial_template_id={0}",
    get_variable_validity_commercial_template: "/commercial-templates/variable-validitys/search?commercial_template_id={0}&state={1}",
    get_commercial_template_commercial_data_search: "/commercial-templates/commercial-datas/search?commercial_template_id={0}",
    get_commercial_template_prospect_document_search: "/commercial-templates/prospect-documents/search?commercial_template_id={0}",
    post_commercial_template: "/commercial-templates/unified",
    get_commercial_template_history: "/commercial-templates/history/find-all?commercial_template_id={0}&pageIndex={1}&pageSize={2}&sort={3}",
    get_commercial_templates_contacts_findall: "/commercial-templates/contacts/find-all/?commercial_template_id={0}&pageIndex={1}&pageSize={2}&sort={3}",
    get_commercial_templates_mails_findall: "/commercial-templates/mails/find-all/?commercial_template_id={0}&pageIndex={1}&pageSize={2}&sort={3}",
    get_report_metrics_search: "/template-history-reports/list-report?flag={0}&cod_c_plant_id={1}&razon_social={2}&nom_comercial={3}&inmueble={4}&local={5}&tipo_fecha={6}&fecha_inicio={7}&fecha_fin={8}&pageIndex={9}&pageSize={10}&sort={11}",
    get_report_metrics_findall: "/template-history-reports/list-export?flag={0}&cod_c_plant_id={1}&razon_social={2}&nom_comercial={3}&inmueble={4}&local={5}&tipo_fecha={6}&fecha_inicio={7}&fecha_fin={8}&rows={9}&userId={10}",
    post_report_metrics: "/template-history-reports/excel-report-history",
    put_commercial_templates_approved: "/commercial-templates/work-flow/approved",
    put_commercial_templates_observe: "/commercial-templates/work-flow/observed",
    put_commercial_templates_annulled: "/commercial-templates/work-flow/annulled",
    get_contracts_marketplace_findall: "/contracts/market-place/find-all?contractId={0}&contractVersion={1}&contractModification={2}&ruc={3}&state={4}&startDate={5}&endDate={6}&businessName={7}&tradename={8}&pageIndex={9}&pageSize={10}&sortProperty=contract_start_date%20DESC",
    get_contracts_marketplace_search: "/contracts/market-place/search?contractId={0}&contractVersion={1}&contractModification={2}&ruc={3}&state={4}&startDate={5}&endDate={6}&businessName={7}&tradename={8}",
    get_contracts_tradenames_findall: "/contracts/tradenames/find-all/?contractId={0}&contractVersion={1}&contractModification={2}&pageIndex={3}&pageSize={4}&sort={5}",
    get_contracts_marketplace_search_by_id: "/contracts/market-place/search?contractId={0}&contractVersion={1}&contractModification={2}",
    get_contracts_addresses_search: "/contracts/addresses/search?contractId={0}&contractVersion={1}&contractModification={2}",
    get_contracts_contacts_search: "/contracts/contacts/search?contractId={0}&contractVersion={1}&contractModification={2}",
    get_contracts_commision_fixed_search: "/contracts/fixed-commission-ranges/search?contractId={0}&contractVersion={1}&contractModification={2}",
    get_contracts_commision_variable_search: "/contracts/variable-commission-ranges/search?contractId={0}&contractVersion={1}&contractModification={2}",
    get_contracts_platforms_search: "/contracts/platforms/search?contractId={0}&contractVersion={1}&contractModification={2}",
    get_contracts_mails_search: "/contracts/mails/search?contractId={0}&contractVersion={1}&contractModification={2}",
    get_contracts_tradenames_search: "/contracts/tradenames/search/?contractId={0}&contractVersion={1}&contractModification={2}",
    get_contracts_document_search: "/contracts/documents/search?contractId={0}&contractVersion={1}&contractModification={2}",
    get_contracts_history: "/contracts/history/find-all?contractId={0}&contractVersion={1}&contractModification={2}&pageIndex={3}&pageSize={4}&sort={5}",
    post_contracts_update_marketplace_unified: "/contracts/market-place/unified",
    get_contracts_export_validities: "/contracts/market-place/export-validities?ruc={0}&state={1}",
    put_upload_validity: "/contracts/market-place/validities",
    get_contracts_economid_conditions_search: "/economics-conditions/search?contractId={0}&contractVersion={1}&contractModification={2}&sortProperty=category_name%20ASC",
    get_contracts_categories_search: "/contracts/market-place/categories/search?typeSeller={0}&sortProperty=category_name%20ASC",
    get_commercial_templates_findall: "/commercial-templates/find-all?commercial_template_id={0}&customer_id={1}&tradename_id={2}{3}{4}{5}&pageIndex={6}&pageSize={7}&sort={8}",
    get_exception_template_findall: "/template/exception-report?contractTemplateId={0}&contractId={1}&businessName={2}&tradeName={3}&realEstate={4}&local={5}&state={6}&executive={7}&templateType={8}&dateType={9}&startDate={10}&endDate={11}&pageIndex={12}&pageSize={13}&sort={14}",
    get_exception_template_export: "/template/exception-report/export-file?contractTemplateId={0}&contractId={1}&businessName={2}&tradeName={3}&realEstate={4}&local={5}&state={6}&executive={7}&templateType={8}&dateType={9}&startDate={10}&endDate={11}",
    get_contracts_export_all: "/contracts/export-all?contractId={0}&contractVersion={1}&contractModification={2}&ruc={3}&state={4}&startDate={5}&endDate={6}&businessName={7}&tradename={8}&sortProperty=contract_start_date%20DESC",
    put_contracts_ranges_actived: "/contracts/market-place/on-active-term",
    get_contracts_accountBank_search: "/contracts/bank-accounts/search?contractId={0}&contractVersion={1}&contractModification={2}",
    get_category_commission: "/contracts/market-place/categories/search-level?typeSeller={0}&level={1}",
    get_pre_contract_findall: "/pre-contract/find-all?ruc={0}&business_name={1}&tradename={2}&contract_start_date={3}&contract_end_date={4}&pageIndex={5}&pageSize={6}&state={7}",
    get_pre_contract_tradename_search: "/pre-contract/tradenames/search?state={0}",
    get_pre_contract_search: "/pre-contract/search?state={0}",
    get_pre_contract_download_template_sellercenter: "/pre-contract/download-template-seller-center",
    get_pre_contract_download_template_vtex: "/pre-contract/download-template-vtex",
    get_pre_contract_download_template_vtex_to_vtex: "/pre-contract/download-template-vtex-to-vtex",
    post_pre_contract_create_masive: "/pre-contract/create-masive",
    post_pre_contract_send_precontract: "/pre-contract/send-precontract",
    put_pre_contract_update_massive_state: "/pre-contract/update-massive-state",
    get_guarantee_type_payment_template: '/guarantee-type-payment-template/search',
    get_contracts_search: '/',
    get_contracts_template_current_situation: '/template/current-situation',
    get_contracts_current_situation: '/current-situation',
    get_contracts_representative: '/representatives/search',
    get_contracts_credit_evaluation_sentinel: '/template/credit-evaluation',
    get_contracts_template_search_integrator: '/template/search-integrator',
    post_contracts_template_post_integrator: '/template/unified',
    get_contracts_template_variable_rent_range_type: '/contract-template-variable-rents/range-types/search',
    get_contract_template_variable_rent_selling_type: '/contract-template-variable-rents/selling-types/search',
    get_item_details_search: '/item-details/search',
    get_item_subtype_loads_search: '/item-subtype-loads/search',
    get_type_load_details_search: '/type-load-details/search',
    get_item_insurance_policies_search: '/item-insurance-policies/search',
    get_fixed_rent_validities_search: '/contract-template-fixed-rents/validities/search',
    
    get_contract_template: '/template',
    get_contract_template_consumptions_search: '/contract-template-consumptions/search',
    get_contract_template_services_search:'/contract-template-services/search',
    get_contract_template_revision_projects_search: '/contract-template-revision-projects/search',
    get_contract_template_key_rights_search: '/contract-template-key-rights/search',
    get_contract_template_air_conditioner_connections_search: '/template-air-conditioner-connections/search',
    get_contract_template_construction_costs_search: '/contract-template-construction-costs/search',
    get_contract_template_water_valves_search: '/contract-template-water-valves/search',    

    get_contracts_template_promotion_expense_search_integrator:'/template-promotion-expenses/search-integrator/{0}',
    get_contracts_template_common_expense_search_integrator:'/template-common-expenses/search-integrator/{0}',
    get_contracts_template_variable_rent_search_integrator: '/contract-template-variable-rents/search-integrator/{0}',
    get_contracts_template_variable_rent_search: '/contract-template-variable-rents/search',
    get_contracts_template_fixed_rent_search_integrator: '/contract-template-fixed-rents/search-integrator/{0}',
    get_contracts_template_validity_search: '/contract-template-validities/search',

    get_contracts_template_guarantee_search_integrator: '/template-guarantees/search-integrator/{0}',
    post_contracts_upload_doc_guarantee: '/contract-upload-doc-guarantees',
    put_contracts_upload_doc_guarantee: '/contract-upload-doc-guarantees',
    get_contracts_template_guarantee_byid: '/contract-upload-doc-guarantees/{0}',

    get_contracts_template_search: '/template/search',
    get_contracts_template_addendum_search: '/template-addendums/search',
    get_contracts_template_air_conditioner_search: '/template-air-conditioners/search',
    get_contracts_template_mall_air_conditioner_search: '/contract-template-mall-air-conditioners/search',
    get_contracts_template_promotion_expense_type_search: '/template-promotion-expense-types/search',
    get_contracts_template_representative_search: '/contract-template-representatives/search',

    get_contracts_template_multiple_exception_adden: '/template/multiple-exception-adden',
    get_contracts_template_exception_search_integrator: '/contract-template-exceptions/search-integrator/{0}',

    get_contracts_guarantess_search: '/guarantees/search',
    
    post_contracts_template_validity_unified: '/contract-template-validities/unified',
    post_contracts_template_fixed_rent_unified: '/contract-template-fixed-rents/unified',
    post_contracts_template_variable_rent_unified: '/contract-template-variable-rents/unified',
    post_contracts_template_common_expense_unified: '/template-common-expenses/unified',
    post_contracts_template_promotion_expense_unified: '/template-promotion-expenses/unified',

    post_contracts_template_consumption_unified: '/contract-template-consumptions/unified',
    post_contracts_template_other_concepts_unified: '/template/unified-other-concepts',
    post_contracts_template_exception_unified: '/contract-template-exceptions/unified',
    post_contracts_template_guarantee_unified: '/template-guarantees/unified',

    get_contracts_revision_project_search: '/revision-projects/search',
    get_contracts_visa_guarantee_search: '/contract-visa-guarantee/search',
    get_contracts_fixed_rent_search: '/fixed-rents/search',
    get_contract_template_fixed_rent_search: '/contract-template-fixed-rents/search',
    post_contracts_template_send: '/template/send',
    get_contracts_warranty_tray_search: '/contract-warranty-trays/search',
    post_contracts_send_credit_unified: '/contract-send-credit-unified',
    get_contracts_template_guarantee_search: '/template-guarantees/search',
    get_contracts_service_search: '/service?ContractId={0}&ContractVersion={1}&ContractModification={2}',
    get_contracts_key_right_search_standard: '/contract-key-rights/search-standard',
    get_contracts_template_common_expense_search: '/template-common-expenses/search',
    get_contracts_template_promotion_expense_search: '/template-promotion-expenses/search',
    get_contract_template_fixed_rent_detail_search: '/contract-template-fixed-rents/details/search',
    get_contracts_template_download_detail: '/template/download-contract-template-detail',
    get_contracts_template_history_search: '/contract-template-historys/search',

    get_contracts_fixed_rent_search_integrator: '/fixed-rents/search-integrator',
    get_contracts_variable_rent_search_integrator: '/variable-rents/search-integrator',
    get_contracts_common_expense_search_integrator: '/common-expenses/search-integrator',
    get_contracts_promotion_expense_search_integrator: '/promotion-funds/search-integrator',
    get_contracts_consumption_search_integrator: '/consumptions/search-integrator',
    get_contracts_additional_concept: '/additional-concepts?ContractId={0}&ContractVersion={1}&ContractModification={2}',
    get_contracts_validity_search: '/validity/search',
    post_contracts_visa_guarantee: '/contract-visa-guarantee',
    post_contracts_template_approve: '/template/approve',
    post_contracts_template_disapprove: '/template/disapprove',
    post_contracts_template_urgency: '/template-urgencies',
    put_contracts_template_urgency: '/template-urgencies',
    get_contracts_template_urgency_search: '/template-urgencies/search',

    put_contract_template: '/template',

    get_contracts_template_credit_evaluation_download: '/template/download-template-credit-evaluation/{0}',
    get_contracts_multiple_exception_template_advance: '/template/multiple-exception-template-advanced'
  },
  storage: {
    get_file_url: "/get-file-url/{0}",
  },
  security: {
    get_commercial_executive: "/users/search/profile?profile={0}&status={1}",
  }
}
export const cacheRedisUrl = 'https://api.realplazalabs.com/common/cache/';
export const appAdvanceNet = 'http://localhost:5076/';
export const keyAdvanceAngularContracts = 'advance-angular-contracts';
export const keyAdvanceAngularBilling = 'advance-angular-billing';
export const appAdvanceAngularBilling = 'http://localhost:4200/';

export const identityUrl = 'https://api.realplazalabs.com/v1/identity';
export const identityType = 'refresh_token';
export const identityClientId = 'realplaza.advance';
export const identityClientSecret = 'E64410FE-554B-48D0-9DA7-38D6BB9614F5';